<?php

namespace PHPMaker2025\pssk2025;

// Navbar menu
$topMenu = new Menu("navbar", true, true);
echo $topMenu->toScript();

// Sidebar menu
$sideMenu = new Menu("menu", true, false);
$sideMenu->addMenuItem(48, "mi_dashboard2", $Language->menuPhrase("48", "MenuText"), "dashboard2", -1, substr("mi_dashboard2", strpos("mi_dashboard2", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}dashboard.php'), false, false, "fa-gauge", "", false, true);
$sideMenu->addMenuItem(4, "mi_home", $Language->menuPhrase("4", "MenuText"), "home", -1, substr("mi_home", strpos("mi_home", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}home.php'), false, false, "fa-home", "", false, true);
$sideMenu->addMenuItem(46, "mci_Master", $Language->menuPhrase("46", "MenuText"), "", -1, substr("mci_Master", strpos("mci_Master", "mi_") + 3), true, false, true, "fa-book", "", false, true);
$sideMenu->addMenuItem(18, "mi_beasiswa", $Language->menuPhrase("18", "MenuText"), "beasiswalist", 46, substr("mi_beasiswa", strpos("mi_beasiswa", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}beasiswa'), false, false, "fa-money-check-dollar", "", false, true);
$sideMenu->addMenuItem(20, "mi_daftar_matakuliah", $Language->menuPhrase("20", "MenuText"), "daftarmatakuliahlist", 46, substr("mi_daftar_matakuliah", strpos("mi_daftar_matakuliah", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}daftar matakuliah'), false, false, "fa-file", "", false, true);
$sideMenu->addMenuItem(33, "mi_tahun_akademik", $Language->menuPhrase("33", "MenuText"), "tahunakademiklist", 46, substr("mi_tahun_akademik", strpos("mi_tahun_akademik", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}tahun_akademik'), false, false, "fa-regular fa-calendar", "", false, true);
$sideMenu->addMenuItem(31, "mi_penyakit", $Language->menuPhrase("31", "MenuText"), "penyakitlist", 46, substr("mi_penyakit", strpos("mi_penyakit", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}penyakit'), false, false, "fa-solid fa-viruses", "", false, true);
$sideMenu->addMenuItem(47, "mci_Data", $Language->menuPhrase("47", "MenuText"), "", -1, substr("mci_Data", strpos("mci_Data", "mi_") + 3), true, false, true, "fa-building-columns", "", false, true);
$sideMenu->addMenuItem(17, "mi_annex", $Language->menuPhrase("17", "MenuText"), "annexlist", 47, substr("mi_annex", strpos("mi_annex", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}annex'), false, false, "fa-file", "", false, true);
$sideMenu->addMenuItem(24, "mi_dosen", $Language->menuPhrase("24", "MenuText"), "dosenlist", 47, substr("mi_dosen", strpos("mi_dosen", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}dosen'), false, false, "fa-users", "", false, true);
$sideMenu->addMenuItem(28, "mi_mahasiswa", $Language->menuPhrase("28", "MenuText"), "mahasiswalist", 47, substr("mi_mahasiswa", strpos("mi_mahasiswa", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}mahasiswa'), false, false, "fa-graduation-cap", "", false, true);
$sideMenu->addMenuItem(19, "mi_cuti_akademik", $Language->menuPhrase("19", "MenuText"), "cutiakademiklist", 47, substr("mi_cuti_akademik", strpos("mi_cuti_akademik", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}cuti_akademik'), false, false, "fa-file", "", false, true);
$sideMenu->addMenuItem(25, "mi_karya_ilmiah", $Language->menuPhrase("25", "MenuText"), "karyailmiahlist", 47, substr("mi_karya_ilmiah", strpos("mi_karya_ilmiah", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}karya_ilmiah'), false, false, "fa-layer-group", "", false, true);
$sideMenu->addMenuItem(26, "mi_kemahasiswaan", $Language->menuPhrase("26", "MenuText"), "kemahasiswaanlist", 47, substr("mi_kemahasiswaan", strpos("mi_kemahasiswaan", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}kemahasiswaan'), false, false, "fa-user-tie", "", false, true);
$sideMenu->addMenuItem(27, "mi_kesehatan_mahasiswa", $Language->menuPhrase("27", "MenuText"), "kesehatanmahasiswalist", 47, substr("mi_kesehatan_mahasiswa", strpos("mi_kesehatan_mahasiswa", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}kesehatan_mahasiswa'), false, false, "fa-hospital-user", "", false, true);
$sideMenu->addMenuItem(29, "mi_mata_kuliah", $Language->menuPhrase("29", "MenuText"), "matakuliahlist", 47, substr("mi_mata_kuliah", strpos("mi_mata_kuliah", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}mata_kuliah'), false, false, "fa-file-pen", "", false, true);
$sideMenu->addMenuItem(30, "mi_pembimbingan", $Language->menuPhrase("30", "MenuText"), "pembimbinganlist", 47, substr("mi_pembimbingan", strpos("mi_pembimbingan", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}pembimbingan'), false, false, "fa-user-pen", "", false, true);
$sideMenu->addMenuItem(32, "mi_semester_antara", $Language->menuPhrase("32", "MenuText"), "semesterantaralist", 47, substr("mi_semester_antara", strpos("mi_semester_antara", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}semester_antara'), false, false, "fa-calendar-day", "", false, true);
$sideMenu->addMenuItem(34, "mi_ujian_tahap_bersama", $Language->menuPhrase("34", "MenuText"), "ujiantahapbersamalist", 47, substr("mi_ujian_tahap_bersama", strpos("mi_ujian_tahap_bersama", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}ujian_tahap_bersama'), false, false, "fa-book-open-reader", "", false, true);
$sideMenu->addMenuItem(16, "mi_theuserprofile", $Language->menuPhrase("16", "MenuText"), "theuserprofilelist", -1, substr("mi_theuserprofile", strpos("mi_theuserprofile", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}theuserprofile'), false, false, "fa-user", "", false, true);
$sideMenu->addMenuItem(5, "mi_help_categories", $Language->menuPhrase("5", "MenuText"), "helpcategorieslist", -1, substr("mi_help_categories", strpos("mi_help_categories", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}help_categories'), false, false, "fa-book", "", false, true);
$sideMenu->addMenuItem(6, "mi_help", $Language->menuPhrase("6", "MenuText"), "helplist?cmd=resetall", 5, substr("mi_help", strpos("mi_help", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}help'), false, false, "fa-book", "", false, true);
$sideMenu->addMenuItem(13, "mci_Terms_and_Condition", $Language->menuPhrase("13", "MenuText"), "javascript:void(0);|||getTermsConditions();return false;", 5, substr("mci_Terms_and_Condition", strpos("mci_Terms_and_Condition", "mi_") + 3), true, false, true, "fas fa-cannabis", "", false, true);
$sideMenu->addMenuItem(14, "mci_About_Us", $Language->menuPhrase("14", "MenuText"), "javascript:void(0);|||getAboutUs();return false;", 5, substr("mci_About_Us", strpos("mci_About_Us", "mi_") + 3), true, false, true, "fa-question", "", false, true);
$sideMenu->addMenuItem(12, "mci_ADMIN", $Language->menuPhrase("12", "MenuText"), "", -1, substr("mci_ADMIN", strpos("mci_ADMIN", "mi_") + 3), true, false, true, "fa-key", "", false, true);
$sideMenu->addMenuItem(1, "mi_users", $Language->menuPhrase("1", "MenuText"), "userslist?cmd=resetall", 12, substr("mi_users", strpos("mi_users", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}users'), false, false, "fa-user", "", false, true);
$sideMenu->addMenuItem(3, "mi_userlevels", $Language->menuPhrase("3", "MenuText"), "userlevelslist", 12, substr("mi_userlevels", strpos("mi_userlevels", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}userlevels'), false, false, "fa-tags", "", false, true);
$sideMenu->addMenuItem(2, "mi_userlevelpermissions", $Language->menuPhrase("2", "MenuText"), "userlevelpermissionslist", 12, substr("mi_userlevelpermissions", strpos("mi_userlevelpermissions", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}userlevelpermissions'), false, false, "fa-file", "", false, true);
$sideMenu->addMenuItem(8, "mi_settings", $Language->menuPhrase("8", "MenuText"), "settingslist", 12, substr("mi_settings", strpos("mi_settings", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}settings'), false, false, "fa-tools", "", false, true);
$sideMenu->addMenuItem(7, "mi_languages", $Language->menuPhrase("7", "MenuText"), "languageslist", 12, substr("mi_languages", strpos("mi_languages", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}languages'), false, false, "fa-flag", "", false, true);
$sideMenu->addMenuItem(15, "mi_announcement", $Language->menuPhrase("15", "MenuText"), "announcementlist", 12, substr("mi_announcement", strpos("mi_announcement", "mi_") + 3), AllowListMenu('{0043A1E5-239B-4C96-BCBF-CDBFE8DDD409}announcement'), false, false, "fas fa-bullhorn", "", false, true);
echo $sideMenu->toScript();
